version: 2.1

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  py36:
    docker:
      - image: circleci/python:3.6

  cloudify-machine:
    machine:
      image: ubuntu-1604:201903-01


commands:

  validate_examples:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - attach_workspace:
          at: workspace
      - run:
          name: Set Python
          command: |
            if ! pyenv -v COMMAND &> /dev/null
            then
                echo "pyenv could not be found"
                exit
            else
                pyenv global 3.6.5
            fi
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: pip install -U pytest==4.6.3 pyyaml==4.2b4 cryptography==3.2.1
      - run:
          name: download manager docker image
          command:  docker pull cloudifyplatform/premium-cloudify-manager-aio:latest
#      - run:
#          name: load docker image
#          command: docker load -i cloudify-manager-aio-docker-5.1.0.dev1.tar
#      - run:
#          name: retain space by dumping the tar
#          command: rm cloudify-manager-aio-docker-5.1.0.dev1.tar
      - run:
          name: show images
          command: docker images
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudifyplatform/premium-cloudify-manager-aio
      - run:
          name: wait for starter
          command: docker exec -it cfy_manager cfy_manager wait-for-starter
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip --user
      - run: pytest -s .cicd/test_examples.py -k 'test_blueprint_validation or test_versions'

  test_openshift:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - attach_workspace:
          at: workspace
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: pip install -U cloudify==5.1 pytest==4.6.3 pyyaml==4.2b4
      - run:
          name: download manager docker image
          command:  docker pull cloudifyplatform/premium-cloudify-manager-aio:latest
#      - run:
#          name: load docker image
#          command: docker load -i cloudify-manager-aio-docker-5.1.0.dev1.tar
#      - run:
#          name: retain space by dumping the tar
#          command: rm cloudify-manager-aio-docker-5.1.0.dev1.tar
      - run:
          name: show images
          command: docker images
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudifyplatform/premium-cloudify-manager-aio
      - run:
          name: wait for starter
          command: docker exec -it cfy_manager cfy_manager wait-for-starter
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip --user
      - run: pytest -s .cicd/test_examples.py -k 'test_openshift'

  test_examples:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - attach_workspace:
          at: workspace
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: pip install -U cloudify==5.1 pytest==4.6.3 pyyaml==4.2b4
      - run:
          name: download manager docker image
          command:  docker pull cloudifyplatform/premium-cloudify-manager-aio:latest
#      - run:
#          name: load docker image
#          command: docker load -i cloudify-manager-aio-docker-5.1.0.dev1.tar
#      - run:
#          name: retain space by dumping the tar
#          command: rm cloudify-manager-aio-docker-5.1.0.dev1.tar
      - run:
          name: show images
          command: docker images
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudifyplatform/premium-cloudify-manager-aio
      - run:
          name: wait for starter
          command: docker exec -it cfy_manager cfy_manager wait-for-starter
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip --user
      - run: pytest -s .cicd/test_examples.py -k 'test_getting_started'

  release_examples:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - attach_workspace:
          at: workspace
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: pip install -U cloudify==5.1 pytest==4.6.3
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip --user
      - run: python .cicd/package_examples.py

jobs:

  virtual-machine-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: virtual-machine
    steps:
      - checkout
      - validate_examples

  utilities-examples-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: utilities-examples
    steps:
      - checkout
      - validate_examples

  hello-world-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: hello-world
    steps:
      - checkout
      - validate_examples

  rest-plugin-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: rest-plugin
    steps:
      - checkout
      - validate_examples

  prometheus-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: prometheus
    steps:
      - checkout
      - validate_examples

  example-network-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: example-network
    steps:
      - checkout
      - validate_examples

  vnf-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: vnf
    steps:
      - checkout
      - validate_examples

  automation-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: automation
    steps:
      - checkout
      - validate_examples

  kubernetes-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: kubernetes
    steps:
      - checkout
      - validate_examples

  infoblox-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: infoblox
    steps:
      - checkout
      - validate_examples

  getting-started-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: getting-started
    steps:
      - checkout
      - validate_examples

  db-lb-app-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: db-lb-app
    steps:
      - checkout
      - validate_examples

  docker-blueprint-validation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      VALIDATION_TEST_CATEGORY: docker
    steps:
      - checkout
      - validate_examples

  getting-started-aws:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: aws
    steps:
      - checkout
      - test_examples

  getting-started-aws-terraform:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: aws
    steps:
      - checkout
      - test_examples

  getting-started-aws-cloudformation:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: aws
    steps:
      - checkout
      - test_examples

  getting-started-openstack:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: openstack
    steps:
      - checkout
      - test_examples

  getting-started-azure:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: azure
    steps:
      - checkout
      - test_examples

  getting-started-azure-arm:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: azure
    steps:
      - checkout
      - test_examples

  getting-started-gcp:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: gcp
    steps:
      - checkout
      - test_examples

  getting-started-ansible:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
      IAAS: ansible
    steps:
      - checkout
      - test_examples

  openshift:
    executor: cloudify-machine
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - test_openshift

  release:
    executor: py36
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - release_examples

workflows:
  version: 2
  tests:
    jobs:
      - virtual-machine-blueprint-validation
      - utilities-examples-blueprint-validation
      - hello-world-blueprint-validation
      - rest-plugin-blueprint-validation
      - prometheus-blueprint-validation
      - example-network-blueprint-validation
      - vnf-blueprint-validation
      - automation-blueprint-validation
      - kubernetes-blueprint-validation
      - infoblox-blueprint-validation
      - getting-started-blueprint-validation
      - db-lb-app-blueprint-validation
      - docker-blueprint-validation
#      - getting-started-aws:
#          requires:
#            - virtual-machine-blueprint-validation
#            - getting-started-blueprint-validation
#          filters:
#            branches:
#              only: master
#      - getting-started-aws-terraform:
#          requires:
#            - getting-started-aws
#          filters:
#            branches:
#              only: master
#      - getting-started-aws-cloudformation:
#          requires:
#            - getting-started-aws-terraform
#          filters:
#            branches:
#              only: master
#      - getting-started-azure:
#          requires:
#            - getting-started-gcp
#            - virtual-machine-blueprint-validation
#            - getting-started-blueprint-validation
#          filters:
#            branches:
#              only: master
#      - getting-started-azure-arm:
#          requires:
#            - getting-started-azure
#            - virtual-machine-blueprint-validation
#            - getting-started-blueprint-validation
#          filters:
#            branches:
#              only: master
#      - getting-started-gcp:
#          requires:
#            - virtual-machine-blueprint-validation
#            - getting-started-blueprint-validation
#          filters:
#            branches:
#              only: master
#      - getting-started-ansible:
#          requires:
#            - virtual-machine-blueprint-validation
#            - getting-started-blueprint-validation
#            - getting-started-aws-cloudformation
#          filters:
#            branches:
#              only: master
#      - openshift:
#          requires:
#            - kubernetes-blueprint-validation
#          filters:
#            branches:
#              only: master
#      - getting-started-openstack:
#          requires:
#            - virtual-machine-blueprint-validation
#            - getting-started-blueprint-validation
#          filters:
#            branches:
#              only: master
      - release:
          requires:
            - utilities-examples-blueprint-validation
            - hello-world-blueprint-validation
            - rest-plugin-blueprint-validation
            - prometheus-blueprint-validation
            - example-network-blueprint-validation
            - vnf-blueprint-validation
            - automation-blueprint-validation
            - infoblox-blueprint-validation
            - db-lb-app-blueprint-validation
            - docker-blueprint-validation
            - getting-started-aws
            - getting-started-aws-cloudformation
            - getting-started-aws-terraform
            - getting-started-azure
            - getting-started-azure-arm
            - getting-started-gcp
            - getting-started-ansible
            # - openshift
#            - getting-started-openstack
          filters:
            branches:
              only: master
  nightly:
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - virtual-machine-blueprint-validation
      - utilities-examples-blueprint-validation
      - hello-world-blueprint-validation
      - rest-plugin-blueprint-validation
      - prometheus-blueprint-validation
      - example-network-blueprint-validation
      - vnf-blueprint-validation
      - automation-blueprint-validation
      - kubernetes-blueprint-validation
      - infoblox-blueprint-validation
      - getting-started-blueprint-validation
      - db-lb-app-blueprint-validation
      - docker-blueprint-validation
      - getting-started-aws:
          requires:
            - virtual-machine-blueprint-validation
            - getting-started-blueprint-validation
          filters:
            branches:
              only: master
      - getting-started-aws-terraform:
          requires:
            - getting-started-aws
          filters:
            branches:
              only: master
      - getting-started-aws-cloudformation:
          requires:
            - getting-started-aws-terraform
          filters:
            branches:
              only: master
      - getting-started-azure:
          requires:
            - virtual-machine-blueprint-validation
            - getting-started-blueprint-validation
          filters:
            branches:
              only: master
      - getting-started-azure-arm:
          requires:
            - getting-started-azure
            - virtual-machine-blueprint-validation
            - getting-started-blueprint-validation
          filters:
            branches:
              only: master
      - getting-started-gcp:
          requires:
            - virtual-machine-blueprint-validation
            - getting-started-blueprint-validation
          filters:
            branches:
              only: master
      - getting-started-ansible:
          requires:
            - virtual-machine-blueprint-validation
            - getting-started-blueprint-validation
          filters:
            branches:
              only: master
#      - openshift:
#          requires:
#            - kubernetes-blueprint-validation
#          filters:
#            branches:
#              only: master
#      - getting-started-openstack:
#          requires:
#            - virtual-machine-blueprint-validation
#            - getting-started-blueprint-validation
#          filters:
#            branches:
#              only: master
