apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ APP_NAME }}-app"
  labels:
    app: {{ APP_NAME }}
    manager: cloudify
    tier: app
spec:
  selector:
    matchLabels:
      app: {{ APP_NAME }}
      manager: cloudify
      tier: app
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ APP_NAME }}
        manager: cloudify
        tier: app
    spec:
      containers:
      - name: {{ CONTAINER_NAME }}
        image: {{ CONTAINER_IMAGE }}
        ports:
        - containerPort: {{ PORT }}
          name: http-server
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 1
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ APP_NAME }}-svc"
  labels:
    app: {{ APP_NAME }}
    manager: cloudify
    tier: app
spec:
  type: NodePort
  selector:
    app: {{ APP_NAME }}
    manager: cloudify
    tier: app
  ports:
  - port: 80
    targetPort: {{ PORT }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ APP_NAME }}-ingress"
  labels:
    app: {{ APP_NAME }}
    manager: cloudify
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: "{{ APP_NAME }}-svc"
          servicePort: 80
